# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  database.al13.com:
    site_hosts:
      - database.al13.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/database.al13.com.git
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: admin
    admin_email: admin@database.al13.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://database.al13.dev
      wp_siteurl: http://database.al13.dev
      wp_env: development
      db_name: example_dev
      db_user: example_dbuser
      db_password: example_dbpassword
